language: java
sudo: false
script: mvn clean verify
deploy:
  provider: releases
  api_key: "t1cVZ2VhUbbb16YmKJEc"
  file: "target/dataslang_java_tools-jar-width-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
